version: '3.1'

services:
  sbcdrink-api:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.local
    container_name: sbcdrink-api
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ../.env
    volumes:
      - ../:/sbcdrink-api
    networks:
      - sbcdrink-network
    depends_on:
      - sbcdrink-mongo

  sbcdrink-mongo:
    container_name: sbcdrink-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
    networks:
      - sbcdrink-network

  sbcdrink-mongo-express:
    container_name: sbcdrink-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASS
      ME_CONFIG_MONGODB_URL: mongodb://$DB_USER:$DB_PASS@sbcdrink-mongo:$DB_PORT/
    networks:
      - sbcdrink-network
    depends_on:
      - sbcdrink-mongo

networks:
  sbcdrink-network:
