FROM node:18-alpine

ENV NODE_ENV=development

WORKDIR /api

COPY ["package.json", "yarn.lock", "./"]

RUN yarn install
RUN npm install -g ts-node

COPY . .

EXPOSE 8000

# CMD ["yarn", "start"]
CMD ["sleep", "infinity"]

