version: '3.1'

services:
  api:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.local
    container_name: api
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ../.env
    volumes:
      - ../:/api
    networks:
      - sbcdrinkapi
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
    networks:
      - sbcdrinkapi

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASS
      ME_CONFIG_MONGODB_URL: mongodb://$DB_USER:$DB_PASS@mongo:$DB_PORT/
    networks:
      - sbcdrinkapi
    depends_on:
      - mongo

networks:
  sbcdrinkapi:
