FROM node:18-alpine

ENV NODE_ENV=development

RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.6/community' >> /etc/apk/repositories
RUN apk add mongodb-tools

WORKDIR /api

COPY ["package.json", "yarn.lock", "./"]

RUN yarn install
RUN npm install -g ts-node

COPY . .

EXPOSE 8000

# CMD ["yarn", "start"]
CMD ["sleep", "infinity"]

